
import { User, Profile, Skill } from "@/types";

export const mockSkills: Skill[] = [
  { id: "1", name: "JavaScript" },
  { id: "2", name: "TypeScript" },
  { id: "3", name: "React" },
  { id: "4", name: "Node.js" },
  { id: "5", name: "Express" },
  { id: "6", name: "MongoDB" },
  { id: "7", name: "PostgreSQL" },
  { id: "8", name: "GraphQL" },
  { id: "9", name: "Python" },
  { id: "10", name: "Django" },
  { id: "11", name: "Flask" },
  { id: "12", name: "Ruby" },
  { id: "13", name: "Ruby on Rails" },
  { id: "14", name: "Java" },
  { id: "15", name: "Spring" },
  { id: "16", name: "C#" },
  { id: "17", name: ".NET" },
  { id: "18", name: "PHP" },
  { id: "19", name: "Laravel" },
  { id: "20", name: "Go" },
  { id: "21", name: "Rust" },
  { id: "22", name: "Swift" },
  { id: "23", name: "Kotlin" },
  { id: "24", name: "AWS" },
  { id: "25", name: "Azure" },
  { id: "26", name: "Google Cloud" },
  { id: "27", name: "Docker" },
  { id: "28", name: "Kubernetes" },
  { id: "29", name: "CI/CD" },
  { id: "30", name: "Git" },
];

export const mockUsers: User[] = [
  { id: "1", username: "johndoe", email: "john@example.com" },
  { id: "2", username: "janedoe", email: "jane@example.com" },
  { id: "3", username: "bobsmith", email: "bob@example.com" },
  { id: "4", username: "alicejones", email: "alice@example.com" },
  { id: "5", username: "mikebrown", email: "mike@example.com" },
];

export const mockProfiles: Profile[] = [
  {
    id: "1",
    userId: "1",
    name: "John Doe",
    title: "Full Stack Developer",
    bio: "Passionate developer with 5+ years of experience in web development.",
    location: "San Francisco, CA",
    avatar: "https://i.pravatar.cc/150?img=1",
    skills: [mockSkills[0], mockSkills[1], mockSkills[2], mockSkills[3]],
    github: "https://github.com/johndoe",
    linkedin: "https://linkedin.com/in/johndoe",
    website: "https://johndoe.dev",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    userId: "2",
    name: "Jane Doe",
    title: "Backend Developer",
    bio: "Backend specialist with focus on scalable architectures.",
    location: "New York, NY",
    avatar: "https://i.pravatar.cc/150?img=5",
    skills: [mockSkills[3], mockSkills[4], mockSkills[5], mockSkills[26]],
    github: "https://github.com/janedoe",
    linkedin: "https://linkedin.com/in/janedoe",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    userId: "3",
    name: "Bob Smith",
    title: "Frontend Developer",
    bio: "UI/UX enthusiast creating beautiful and functional interfaces.",
    location: "Seattle, WA",
    avatar: "https://i.pravatar.cc/150?img=3",
    skills: [mockSkills[0], mockSkills[2], mockSkills[7]],
    github: "https://github.com/bobsmith",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    userId: "4",
    name: "Alice Jones",
    title: "DevOps Engineer",
    bio: "Building and maintaining robust CI/CD pipelines and infrastructure.",
    location: "Austin, TX",
    avatar: "https://i.pravatar.cc/150?img=9",
    skills: [mockSkills[26], mockSkills[27], mockSkills[28], mockSkills[29]],
    linkedin: "https://linkedin.com/in/alicejones",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    userId: "5",
    name: "Mike Brown",
    title: "Mobile Developer",
    bio: "Creating native and cross-platform mobile applications.",
    location: "Chicago, IL",
    avatar: "https://i.pravatar.cc/150?img=8",
    skills: [mockSkills[21], mockSkills[22], mockSkills[2]],
    github: "https://github.com/mikebrown",
    linkedin: "https://linkedin.com/in/mikebrown",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
